name: Test Framework Comparisons

on:
  push:
    branches: [ master ]

jobs:
  pytest:
    name: Linter and Pytest
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    environment: Prod

    steps:
      - name: Linter & Pytest
        env:
          GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_EVENT_NAME: ${{ secrets.GITHUB_EVENT_NAME }}
        run: echo "$GITHUB_RUN_ID $GITHUB_REPOSITORY $GITHUB_EVENT_NAME"

      - uses: actions/checkout@v2
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install cryptography==38.0.4
          if [ -f unit-test-service/requirements.txt ]; then pip install -r unit-test-service/requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Unit Test with pytest
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
          USER_AGENT: ${{ secrets.USER_AGENT }}

        run: |
          echo "$PYTHONPATH $USER_AGENT $PWD"
          pytest unit-test-service/tests_pytest/conftest.py -vv -o log_cli=true

  unittest:
    name: Linter and Unittest
    runs-on: ubuntu-latest
    needs: pytest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    environment: Prod

    steps:
      - name: Linter & Unittest
        env:
          GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_EVENT_NAME: ${{ secrets.GITHUB_EVENT_NAME }}
        run: echo "$GITHUB_RUN_ID $GITHUB_REPOSITORY $GITHUB_EVENT_NAME"

      - uses: actions/checkout@v2
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install cryptography==38.0.4
          if [ -f unit-test-service/requirements.txt ]; then pip install -r unit-test-service/requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Unit Test with unittest
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
          USER_AGENT: ${{ secrets.USER_AGENT }}

        run: |
          echo "$PYTHONPATH $USER_AGENT $PWD"
          python -m unittest unit-test-service/tests_unittest/conftest.py -vv
          nose2 -s unit-test-service tests_unittest.conftest -vv
  
  testByVersion:
    name: Run test with tox
    runs-on: ubuntu-latest
    needs: unittest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    environment: Prod

    steps:
      - name: Build Python
        env:
          GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_EVENT_NAME: ${{ secrets.GITHUB_EVENT_NAME }}
        run: echo "$GITHUB_RUN_ID $GITHUB_REPOSITORY $GITHUB_EVENT_NAME"

      - uses: actions/checkout@v2
      - name: Set up Python 3.9.14
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.14"

      - uses: actions/checkout@v2
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - uses: actions/checkout@v2
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install cryptography==38.0.4
          if [ -f unit-test-service/requirements.txt ]; then pip install -r unit-test-service/requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Test with tox
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
          USER_AGENT: ${{ secrets.USER_AGENT }}

        run: |
          echo "$PYTHONPATH $USER_AGENT $PWD"
          tox -r
  
  
  dockerImage:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    environment: Docker
    needs: unittest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/test-comparison-framework

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: unit-test-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

        
