
name: Test Framework Comparisons

on:
  push:
    branches: [master]

jobs:
  DEV:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Linter Test
        env:
          GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_EVENT_NAME: ${{ secrets.GITHUB_EVENT_NAME }}
        run: echo "$GITHUB_RUN_ID $GITHUB_REPOSITORY $GITHUB_EVENT_NAME"
